# override default values.yaml in istio release's helm chart
# i.e., release/manifests/charts/istio-operator/values.yaml
#
# this configures the operator and thus istio
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
  labels:
    istio-injection: enabled
spec:
  profile: demo
  values:
    global:
      istioNamespace: istio-system
  meshconfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    # defaultConfig:
    #   tracing:
    #     sampling: 100
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      # k8s:
      #   resources:
      #     limits:
      #       memory: "200Mi"
      #       cpu: "250m"
    pilot:
    - name: pilot
      enabled: true
      # k8s:
      #   resources:
      #     requests:
      #       cpu: 50m
      #       memory: 300Mi
  addonComponents:
    prometheus:
      enabled: true
    grafana:
      enabled: true
    kiali:
      enabled: true
